[tool.black]
line-length = 99
skip-string-normalization = true
target-version = ["py39"]

[tool.mypy]
sqlite_cache = true
ignore_missing_imports = true
show_error_codes = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true
strict_equality = true
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
exclude = "(?x)(^\\. | /\\.)"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
default_section = "THIRDPARTY"
known_first_party = ["publishing_ml", "tests"]

[tool.pydocstyle]
# D202: No blank lines allowed after function docstring
# D203: 1 blank line required before class docstring
# D205: 1 blank line required between summary line and description
# D213: Multi-line docstring summary should start at the second line
# D400: First line should end with a period
# D415: First line should end with a period, question mark, or exclamation point
ignore = "D202,D203,D205,D213,D400,D415"
match = ".*\\.py"

[tool.coverage.run]
branch = true
omit = ["*tests*"]

[tool.pytest.ini_options]
# Считать ошибкой предупреждение о невозможности загрузки репозитория Dagster
filterwarnings = ['error:Error loading repository:UserWarning']
asyncio_mode = 'auto'
