version: '3.8'
services:
  service-db:
    container_name: pg_vector_db
    image: dreg.sbmt.io/dhub/ankane/pgvector
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dreg.sbmt.io/dhub/dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "8182:8080/tcp"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:

# sudo ls /var/lib/docker/volumes - volumes here
# docker run -p 6333:6333 -p 6334:6334 -v $(pwd)/qdrant_storage:/qdrant/storage:z dreg.sbmt.io/dhub/qdrant/qdrant
# docker run --name redis-stack -p 8503:6379 -p 8501:8001 -v $(pwd)/redis_storage/:/data dreg.sbmt.io/dhub/redis/redis-stack:latest